version: '3.9'

services:
  app:
    container_name: dostavka_app_local
    build: 
      context: .
    command: /scripts/run_local.sh
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: 1
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      - db
 
  db:
    container_name: dostavka_db_local
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    
 
    