version: '3.9'

services:
  app:
    build: 
      context: .
    command: /scripts/run_local.sh
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    environment:
      - SECRET_KEY=${}
      - DEBUG=1
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

env_file:
  - env.local
  